name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make and verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y make verilator

    - name: Clone lefou/millw repository
      run: |
        curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/1.1.9/mill-dist-1.1.9-mill.sh -o mill
        chmod +x mill

    - name: Run make checkformat
      run: make checkformat

    - name: Run make test
      run: make test
