name: CI

on:
  push:
    branches:
      - main  # 或者你希望触发 Action 的分支

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install make and verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y make verilator

    - name: Clone lefou/millw repository
      run: |
        git clone https://github.com/lefou/millw.git
        sudo ln -sf $(pwd)/millw/millw /usr/bin/mill

    - name: Run make checkformat
      run: make checkformat

    - name: Run make test
      run: make test
